### ISSUE TITLE
astyle paketiyle ilgili iyileştirmeler

### ISSUE THREAD

**Issue by maidis** [pardus-anka/2013#26]
Sorry, this one a copy&paste work and in Turkish.
- Uygulamanın yeni sürümü, 2.02 çıkmış Pardus deposundaki paket bu sürüme çekilebilirse iyi olur.
- Pardus deposundaki paketin beşinci yayımı 2.04'ü gösteriyor, sanırım bu 2.01 olmalı.
- Şu an uygulamanın depodaki paketiyle birlikte hiçbir belge gelmiyor. Uygulamanın arşivindeki doc dizininde bulunan astyle.html links.html notes.html styles.css index.html license.html news.html scripts.html subversion.html dosyalarının pakete dahil edilmesi iyi olabilir.
- Pakette uygulamanın lisansı olarak LGPLv2 geçiyor, sanırım yeni sürümle uygulamanın lisansı GNU Lesser General Public License (LGPL) Version 3 olmuş ve ayrıca istisna (exception) içeriyor, bu ayrıca belirtilmeli mi bilmiyorum.
- Uygulamanın ismi Artistic Style ama translations.xml'de Astyle olarak geçiyor.

http://astyle.sourceforge.net/
http://hata.pardus.org.tr/show_bug.cgi?id=18975

**Comment by hitaf** [comment]
Sürüm 2.02 ye çekildi.
Lisansı düzeltildi.
Doc dosyaları pakete alındı.
http://git.io/gqhApg
translations.xml düzeltildi.
http://git.io/t326wg
