### ISSUE TITLE
tomcat-servlet-api

### ISSUE THREAD

**Issue by slarikan** [pardus-anka/2013#27]
Libreoffice derlerken tomcat-servlet-api paketi derlenirken hata aldım http://sudrap.org/paste/text/199251/

**Comment by marcin-** [comment]
The problem with build tomcat-servlet-api and others java packages exists when "sudo pisi build" or "sudo pisi emerge" is used.
Try to use "su -" or login as root then "pisi bi" or "pisi em" tomcat-servlet-api.
When sudo is used java environmental variables aren't exported. The variables which should be set are in /etc/env.d/20java_jre and /etc/env.d/21java_jdk.

**Comment by slarikan** [comment]
sudo pisi em libreoffice -d
pisi lr
rootfs [etkin]
   http://anka.pardus-linux.org/2013/rootfs-repo/pisi-index.xml.xz
2013 [etkin]
   https://raw.github.com/pardus-anka/2013/master/pisi-index.xml.xz
kde [etkin]
   http://anka.pardus-linux.org/2013/rootfs-kde/pisi-index.xml.xz

**Comment by slarikan** [comment]
su - ile root ollunca paket derlendi hatanın kapatılması lazım.
