### ISSUE TITLE
New version: AstroMenace

### ISSUE THREAD

**Issue by maidis** [pardus-anka/2013#37]
AstroMenace version 1.3 build 121021 is available for a while. Overall changes:
- Added Xinerama/TwinView support.
- Added multilingual support (en/de/ru), all language data files merged with main VFS data file.
- Added VFS game data file creation feature.
- Added FreeType2 support for all font rendering, 7 ttf fonts added to game data file.
- Added current OS keyboard layout support for Profile name input.
- Added soft shadows (Shadow Mapping with PCF).

http://www.viewizard.com/astromenace/

**Comment by maidis** [comment]
Yesterday 1.3.1 relased.

**Comment by marcin-** [comment]
https://github.com/pardus-anka/2013/commit/00283420498b1ebe3e264a9e723d183d2c942b17
