### ISSUE TITLE
package-manager hatası, python-qt 4.9.5 üzerinde

### ISSUE THREAD

**Issue by darth-enoch** [pardus-anka/2013#43]
Kendi sistemimde denediğim ufak tefek derlemelerde, python-qt 4.9.5 ve sip 4.14.1 kuruluyken, package-manager'ın şu hatayı verdiğini gördüm:

the sip module implements api v9.0 to v9.1 but the pyqt4.qtcore module requires api v8.1

Deponuzda da sanırım bu sürümler var. Bilgilendirmek istedim. Saygılar.

**Comment by marcin-** [comment]
https://github.com/pardus-anka/2013/commit/e9f3251c8ef05560384cd346ff808a0f72fbdb94
