### ISSUE TITLE
New version: Calligra

### ISSUE THREAD

**Issue by maidis** [pardus-anka/2013#47]
Calligra has a new version for a while. It would be nice to update the calligra package. Also package needs some more cosmetic fixes. All localized text must be in only translations.xml, etc...

http://www.calligra.org/news/calligra-2-5-4-released/
https://github.com/pardus-anka/2013/commit/010e310d4a93d2c3829a2fd549e1971112e00a4e

**Comment by namso-01** [comment]
101469c
