### ISSUE TITLE
update networkmanager, and network-manager-applet, please.

### ISSUE THREAD

**Issue by suvari** [pardus-anka/2013#56]
Rootfs.02, huawei e177 usb modemi, internete bağlar bağlamaz tekrar koparıyor, nmaplepet kurulmasıyla da sonuç değişmiyor, herhangi bir ayar değişikliği ile çözülmüyor.
2011.2'de

2011.2'de ve oradan 2012'de geçtiğimiz anka'da, bu problem basitçe düzeliyordu: e177 nin cd özelliğini kaldırıp takınca, ileri düğmeleriyle kuruluyordu.
Hatta 2011.2 ile, nm applet olmaksızın çalışıyor ve açılışta internete bağlanmış oluyor. Bir güncelleme ile düzelebilir:
http://ftp.gnome.org/pub/GNOME/sources/NetworkManager/0.9/NetworkManager-0.9.7.995.tar.xz
http://ftp.gnome.org/pub/GNOME/sources/network-manager-applet/0.9/network-manager-applet-0.9.7.995.tar.xz

**Comment by marcin-** [comment]
https://github.com/pardus-anka/2013/commit/da4f87d8093d7b1dd62e528c2565decaa7827079
https://github.com/pardus-anka/2013/commit/faa86c3625f2aa15ff23bae05aef5c6e17770447

**Comment by alick01** [comment]
I setup anka marcin.But ı have this bug.modem e177 provider turkcell.

**Comment by marcin-** [comment]
https://www.dropbox.com/sh/chmfxn7qk7wnco8/1Qcrw47HdH/packages
Could you check these packages?

**Comment by alick01** [comment]
now ı downloaded packages.i'll check.

**Comment by ghost** [comment]
Using 3G are trying to do?

**Comment by alick01** [comment]
I tried. install two packages but devel package require dbus-glib-devel problem did not solve this two packages now download dbus-glib-devel.I will check now

**Comment by alick01** [comment]
I install three packages. but problem did not solve. I create a new network profile and unplug the modem after every change.

**Comment by marcin-** [comment]
http://bugs.pardus-anka.org/index.php?do=details&task_id=5&project=3
