### ISSUE TITLE
New package: ksuperkey

### ISSUE THREAD

**Issue by maidis** [pardus-anka/2013#59]
ksuperkey allows you to open the application launcher in KDE Plasma Desktop using the Super key (also known as the 'Windows key'). Unlike other solutions, it will not affect your current keyboard shortcuts, as the Super key will still act as a modifier when held down.

http://kde-apps.org/content/show.php/ksuperkey?content=154569

**Comment by hitaf** [comment]
http://git.io/wfOzng
