### ISSUE TITLE
Güncel depo

### ISSUE THREAD

**Issue by sametatabasch** [pardus-anka/2013#6]
Burda olan değişikleri  bir depo aracılığıyla takip  edebilirmiyiz ? en güncel anka deposunun adresi nedir ? Kolay gelsin .

**Comment by baDibere** [comment]
Son kullanıcı için duyurabileceğimiz bir depo mevcut değil. Kaynak depoyu eklemek isterseniz https://raw.github.com/pardus-anka/2013/master/pisi-index.xml.xz adresini kullanabilirsiniz. Pardus 2011 için oldukça risklidir. 

Son kullanıcı için hazır olan bir deneme sürümü olduğunda duyurusu yapılacaktır.
