### ISSUE TITLE
Github deposuyla program kurma

### ISSUE THREAD

**Issue by sametatabasch** [pardus-anka/2013#64]
github-anka https://github.com/pardus-anka/2013/raw/master/pisi-index.xml.xz
bu depo ile 
sudo pisi em filezilla -dv komutu ile filezillayı kurmayı denediğimde hata veriyor. Çıktıyı aşağıdaki link ile ekledim aynı şekilde vlc kurulumunuda yapamadım
http://www.ozgurlukicin.org/yapistir/1254/

**Comment by hitaf** [comment]
sudo pisi clean
sudo pisi dc
sudo pisi rdb
komutlarından sonra kurabilirsiniz.
