### ISSUE TITLE
Teamviewer 

### ISSUE THREAD

**Issue by sametatabasch** [pardus-anka/2013#65]
teamviewer anka depolarına eklenebilirmi  acaba

**Comment by ghost** [comment]
https://github.com/pardus-anka/pardususer.de/tree/master/teamviewer
Burada mevcut kendileri, depoya alınması ya da alınmaması ile ilgili bir şey söz konusu değil şuan.

**Comment by sametatabasch** [comment]
buradan kurulumu nasıl  yapacağım ?
