### ISSUE TITLE
Picasa

### ISSUE THREAD

**Issue by sametatabasch** [pardus-anka/2013#66]
Picasa programının anka depolarına girmesi mümkün mü  ?

**Comment by waroi** [comment]
Bence de güzel olurdu, eğer mümkünse :)

**Comment by sametatabasch** [comment]
picasanın linux versiyonu yok  muş  ben var diye biliyordum ozaman başlığı kapatalım kalabalık yapmasın

**Comment by namso-01** [comment]
istediğiniz paket burada https://github.com/pardus-anka/pardususer.de/tree/master/picasa fakat dönüştürme paketleri depoya alınır mı ?

**Comment by slarikan** [comment]
Arşiv adresleri ölü derlemek mümkün  değil
